-- Banco de dados: Supabase PostgreSQL

CREATE TABLE categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    descricao TEXT
);

CREATE TABLE produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(150) NOT NULL,
    descricao TEXT,
    preco NUMERIC(10,2) NOT NULL CHECK (preco >= 0),
    quantidade INTEGER NOT NULL DEFAULT 0 CHECK (quantidade >= 0),
    categoria_id BIGINT NOT NULL,
    CONSTRAINT fk_categoria
        FOREIGN KEY (categoria_id)
        REFERENCES categorias(id)
        ON DELETE CASCADE
);

-- Dados de exemplo
INSERT INTO categorias (nome, descricao) VALUES
('Eletrônicos', 'Produtos eletrônicos e acessórios'),
('Informática', 'Equipamentos e periféricos para computador'),
('Escritório', 'Materiais e itens para escritório');

INSERT INTO produtos (nome, descricao, preco, quantidade, categoria_id) VALUES
('Teclado Mecânico', 'Teclado mecânico para computador', 250.00, 10, 2),
('Mouse Sem Fio', 'Mouse óptico sem fio', 89.90, 20, 2),
('Fone Bluetooth', 'Fone de ouvido sem fio', 199.90, 8, 1),
('Caderno', 'Caderno universitário', 25.00, 30, 3);
